# general configuration
url: www.mit.edu/~maxkw
baseurl: /~maxkw

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/mkw.png"
  # author will appear under the avatar (optional)
  # author: "Compass"
  # tagline will appear under the title (optional)
  tagline: "Max Kleiman-Weiner is a PhD Student at MIT researching the computational cognitive science of social behavior."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: pygments
parse_block_html: true


# Permalinks
permalink: pretty
relative_permalinks: true

scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending
  repository: pdf
  source: ./_bibliography
  bibliography: bibliography.bib
  bibliography_template: "{{reference}} {% if link %}[<a href=\"{{link}}\">pdf</a>]{% endif %}"